categories:
  AI:
    - faiss
    - hnswlib
    - scann
  Bigdata:
  Storage:
  Database:
    - redis
  Media:
  HPC:
    - folly
    - lz4
    - protobuf
    - snappy
    - sonic
    - zstd
  Middleware:
    - brpc
  Toolchain:
  Others:
