categories:
  AI:
    - faiss
    - hnswlib
    - scann
  Bigdata:
  Storage:
  Database:
    - redis
  Media:
  HPC:
    - lz4
    - protobuf
    - snappy
    - zstd
  Middleware:
  Toolchain:
  Others:
