categories:
  AI:
    - faiss
    - hnswlib
    - openviking
    - scann
  Bigdata:
    - flink
  Storage:
  Database:
    - redis
    - mysql
    - rocksdb
    - oceanbase
  Media:
    - x264
    - x265
  HPC:
    - folly
    - lz4
    - protobuf
    - snappy
    - sonic-cpp
    - sonic-go
    - zstd
  Middleware:
    - brpc
    - envoy
    - kubernetes
  Toolchain:
    - openjdk
    - gcc
    - golang
    - glibc
    - python
  Others:
